export const GET_ALL_COLLABORATEUR = 'GET_ALL_COLLABORATEUR';
export const GET_ONE_COLLABORATEUR = 'GET_ONE_COLLABORATEUR';

export const ADD_COLLABORATEUR = 'ADD_COLLABORATEUR';
export const EDIT_COLLABORATEUR = 'EDIT_COLLABORATEUR';
export const REMOVE_COLLABORATEUR = 'REMOVE_COLLABORATEUR';
